#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/_lib.sh"

require_var AWS_PROFILE
require_var AWS_ACCOUNT_ID
require_var AWS_REGION
require_var ECR_BACKEND_REPO
require_var BACKEND_IMAGE_TAG
require_var APP_RUNNER_SERVICE_ARN
require_var APP_RUNNER_ECR_ACCESS_ROLE_ARN
require_var MBTA_API_KEY
require_var DATABASE_URL

REPO_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_BACKEND_REPO"
IMAGE_IDENTIFIER="$REPO_URI:$BACKEND_IMAGE_TAG"

MBTA_RATE_LIMIT_WINDOW_MS="${MBTA_RATE_LIMIT_WINDOW_MS:-60000}"
MBTA_RATE_LIMIT_MAX_REQUESTS="${MBTA_RATE_LIMIT_MAX_REQUESTS:-1000}"
MBTA_MAX_RETRIES="${MBTA_MAX_RETRIES:-4}"
MBTA_RETRY_BASE_DELAY_MS="${MBTA_RETRY_BASE_DELAY_MS:-500}"
MBTA_RETRY_MAX_DELAY_MS="${MBTA_RETRY_MAX_DELAY_MS:-7500}"
LOG_LEVEL="${LOG_LEVEL:-info}"
HOME_SNAPSHOT_TIMEOUT_MS="${HOME_SNAPSHOT_TIMEOUT_MS:-1500}"
HOME_SNAPSHOT_CONCURRENCY="${HOME_SNAPSHOT_CONCURRENCY:-4}"
TRIP_PLANNER_REALTIME="${TRIP_PLANNER_REALTIME:-true}"
OSRM_BASE_URL="${OSRM_BASE_URL:-}"
OSRM_TIMEOUT_MS="${OSRM_TIMEOUT_MS:-1500}"
PGSSLMODE="${PGSSLMODE:-require}"
PGSSLROOTCERT="${PGSSLROOTCERT:-}"
PGSSL_SERVERNAME="${PGSSL_SERVERNAME:-}"
PGSSLREJECTUNAUTHORIZED="${PGSSLREJECTUNAUTHORIZED:-false}"
NODE_TLS_REJECT_UNAUTHORIZED="${NODE_TLS_REJECT_UNAUTHORIZED:-0}"
SKIP_SHAPES_POLLING="${SKIP_SHAPES_POLLING:-}"
SITE_URL="${SITE_URL:-}"
STRIPE_MODE="${STRIPE_MODE:-}"
STRIPE_SECRET_KEY="${STRIPE_SECRET_KEY:-}"
STRIPE_PUBLISHABLE_KEY="${STRIPE_PUBLISHABLE_KEY:-}"
STRIPE_TEST_SECRET_KEY="${STRIPE_TEST_SECRET_KEY:-}"
STRIPE_TEST_PUBLISHABLE_KEY="${STRIPE_TEST_PUBLISHABLE_KEY:-}"
STRIPE_CHECKOUT_WEBHOOK_SIGNING_SECRET="${STRIPE_CHECKOUT_WEBHOOK_SIGNING_SECRET:-}"

tmpfile="$(mktemp)"
trap 'rm -f "$tmpfile"' EXIT

cat > "$tmpfile" <<JSON
{
  "ServiceArn": "$APP_RUNNER_SERVICE_ARN",
  "SourceConfiguration": {
    "ImageRepository": {
      "ImageIdentifier": "$IMAGE_IDENTIFIER",
      "ImageRepositoryType": "ECR",
      "ImageConfiguration": {
        "Port": "4000",
        "RuntimeEnvironmentVariables": {
          "PORT": "4000",
          "MBTA_API_BASE_URL": "https://api-v3.mbta.com",
          "MBTA_API_KEY": "$MBTA_API_KEY",
          "LOG_LEVEL": "$LOG_LEVEL",
          "MBTA_RATE_LIMIT_WINDOW_MS": "$MBTA_RATE_LIMIT_WINDOW_MS",
          "MBTA_RATE_LIMIT_MAX_REQUESTS": "$MBTA_RATE_LIMIT_MAX_REQUESTS",
          "MBTA_MAX_RETRIES": "$MBTA_MAX_RETRIES",
          "MBTA_RETRY_BASE_DELAY_MS": "$MBTA_RETRY_BASE_DELAY_MS",
          "MBTA_RETRY_MAX_DELAY_MS": "$MBTA_RETRY_MAX_DELAY_MS",
          "HOME_SNAPSHOT_TIMEOUT_MS": "$HOME_SNAPSHOT_TIMEOUT_MS",
          "HOME_SNAPSHOT_CONCURRENCY": "$HOME_SNAPSHOT_CONCURRENCY",
          "TRIP_PLANNER_REALTIME": "$TRIP_PLANNER_REALTIME",
          "OSRM_BASE_URL": "$OSRM_BASE_URL",
          "OSRM_TIMEOUT_MS": "$OSRM_TIMEOUT_MS",
          "DATABASE_URL": "$DATABASE_URL",
          "PGSSLMODE": "$PGSSLMODE",
          "PGSSLROOTCERT": "$PGSSLROOTCERT",
          "PGSSL_SERVERNAME": "$PGSSL_SERVERNAME",
          "PGSSLREJECTUNAUTHORIZED": "$PGSSLREJECTUNAUTHORIZED",
          "NODE_TLS_REJECT_UNAUTHORIZED": "$NODE_TLS_REJECT_UNAUTHORIZED",
          "SKIP_SHAPES_POLLING": "$SKIP_SHAPES_POLLING",
          "SITE_URL": "$SITE_URL",
          "STRIPE_MODE": "$STRIPE_MODE",
          "STRIPE_SECRET_KEY": "$STRIPE_SECRET_KEY",
          "STRIPE_PUBLISHABLE_KEY": "$STRIPE_PUBLISHABLE_KEY",
          "STRIPE_TEST_SECRET_KEY": "$STRIPE_TEST_SECRET_KEY",
          "STRIPE_TEST_PUBLISHABLE_KEY": "$STRIPE_TEST_PUBLISHABLE_KEY",
          "STRIPE_CHECKOUT_WEBHOOK_SIGNING_SECRET": "$STRIPE_CHECKOUT_WEBHOOK_SIGNING_SECRET"
        }
      }
    },
    "AutoDeploymentsEnabled": true,
    "AuthenticationConfiguration": {
      "AccessRoleArn": "$APP_RUNNER_ECR_ACCESS_ROLE_ARN"
    }
  }
}
JSON

aws apprunner update-service \
  --cli-input-json "file://$tmpfile" \
  --profile "$AWS_PROFILE" \
  --query "Service.Status" \
  --output text
